// Generated by gencpp from file custom_msgs/DetectionDistance.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_DETECTIONDISTANCE_H
#define CUSTOM_MSGS_MESSAGE_DETECTIONDISTANCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct DetectionDistance_
{
  typedef DetectionDistance_<ContainerAllocator> Type;

  DetectionDistance_()
    : class_id(0)
    , distance(0.0)  {
    }
  DetectionDistance_(const ContainerAllocator& _alloc)
    : class_id(0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _class_id_type;
  _class_id_type class_id;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::custom_msgs::DetectionDistance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::DetectionDistance_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionDistance_

typedef ::custom_msgs::DetectionDistance_<std::allocator<void> > DetectionDistance;

typedef boost::shared_ptr< ::custom_msgs::DetectionDistance > DetectionDistancePtr;
typedef boost::shared_ptr< ::custom_msgs::DetectionDistance const> DetectionDistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::DetectionDistance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::DetectionDistance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::DetectionDistance_<ContainerAllocator1> & lhs, const ::custom_msgs::DetectionDistance_<ContainerAllocator2> & rhs)
{
  return lhs.class_id == rhs.class_id &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::DetectionDistance_<ContainerAllocator1> & lhs, const ::custom_msgs::DetectionDistance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::DetectionDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::DetectionDistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::DetectionDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::DetectionDistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::DetectionDistance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::DetectionDistance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::DetectionDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "175cb11d2b584f9edc572f3c2d08635a";
  }

  static const char* value(const ::custom_msgs::DetectionDistance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x175cb11d2b584f9eULL;
  static const uint64_t static_value2 = 0xdc572f3c2d08635aULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::DetectionDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/DetectionDistance";
  }

  static const char* value(const ::custom_msgs::DetectionDistance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::DetectionDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 class_id\n"
"float32 distance\n"
;
  }

  static const char* value(const ::custom_msgs::DetectionDistance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::DetectionDistance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.class_id);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionDistance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::DetectionDistance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::DetectionDistance_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "class_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.class_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_DETECTIONDISTANCE_H
