// Generated by gencpp from file custom_msgs/DetectionDistanceArray.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_DETECTIONDISTANCEARRAY_H
#define CUSTOM_MSGS_MESSAGE_DETECTIONDISTANCEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <custom_msgs/DetectionDistance.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct DetectionDistanceArray_
{
  typedef DetectionDistanceArray_<ContainerAllocator> Type;

  DetectionDistanceArray_()
    : header()
    , detections()  {
    }
  DetectionDistanceArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::custom_msgs::DetectionDistance_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::custom_msgs::DetectionDistance_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionDistanceArray_

typedef ::custom_msgs::DetectionDistanceArray_<std::allocator<void> > DetectionDistanceArray;

typedef boost::shared_ptr< ::custom_msgs::DetectionDistanceArray > DetectionDistanceArrayPtr;
typedef boost::shared_ptr< ::custom_msgs::DetectionDistanceArray const> DetectionDistanceArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::DetectionDistanceArray_<ContainerAllocator1> & lhs, const ::custom_msgs::DetectionDistanceArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::DetectionDistanceArray_<ContainerAllocator1> & lhs, const ::custom_msgs::DetectionDistanceArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3f1012552fe33467f794d026ae1595f";
  }

  static const char* value(const ::custom_msgs::DetectionDistanceArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3f1012552fe3346ULL;
  static const uint64_t static_value2 = 0x7f794d026ae1595fULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/DetectionDistanceArray";
  }

  static const char* value(const ::custom_msgs::DetectionDistanceArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"DetectionDistance[] detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: custom_msgs/DetectionDistance\n"
"int32 class_id\n"
"float32 distance\n"
;
  }

  static const char* value(const ::custom_msgs::DetectionDistanceArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionDistanceArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::DetectionDistanceArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::DetectionDistanceArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detections: ";
    if (v.detections.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::custom_msgs::DetectionDistance_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.detections[i]);
    }
    if (v.detections.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_DETECTIONDISTANCEARRAY_H
