// Generated by gencpp from file custom_msgs/EncoderTicks.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_ENCODERTICKS_H
#define CUSTOM_MSGS_MESSAGE_ENCODERTICKS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct EncoderTicks_
{
  typedef EncoderTicks_<ContainerAllocator> Type;

  EncoderTicks_()
    : header()
    , ticks(0)
    , delta_ticks(0)  {
    }
  EncoderTicks_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ticks(0)
    , delta_ticks(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _ticks_type;
  _ticks_type ticks;

   typedef int32_t _delta_ticks_type;
  _delta_ticks_type delta_ticks;





  typedef boost::shared_ptr< ::custom_msgs::EncoderTicks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::EncoderTicks_<ContainerAllocator> const> ConstPtr;

}; // struct EncoderTicks_

typedef ::custom_msgs::EncoderTicks_<std::allocator<void> > EncoderTicks;

typedef boost::shared_ptr< ::custom_msgs::EncoderTicks > EncoderTicksPtr;
typedef boost::shared_ptr< ::custom_msgs::EncoderTicks const> EncoderTicksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::EncoderTicks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::EncoderTicks_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::EncoderTicks_<ContainerAllocator1> & lhs, const ::custom_msgs::EncoderTicks_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ticks == rhs.ticks &&
    lhs.delta_ticks == rhs.delta_ticks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::EncoderTicks_<ContainerAllocator1> & lhs, const ::custom_msgs::EncoderTicks_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::EncoderTicks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::EncoderTicks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::EncoderTicks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::EncoderTicks_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::EncoderTicks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::EncoderTicks_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::EncoderTicks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b02ec1224acd3c659bd318623a2c19a2";
  }

  static const char* value(const ::custom_msgs::EncoderTicks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb02ec1224acd3c65ULL;
  static const uint64_t static_value2 = 0x9bd318623a2c19a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::EncoderTicks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/EncoderTicks";
  }

  static const char* value(const ::custom_msgs::EncoderTicks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::EncoderTicks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int32 ticks\n"
"int32 delta_ticks\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_msgs::EncoderTicks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::EncoderTicks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ticks);
      stream.next(m.delta_ticks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EncoderTicks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::EncoderTicks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::EncoderTicks_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ticks: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ticks);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "delta_ticks: ";
    Printer<int32_t>::stream(s, indent + "  ", v.delta_ticks);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_ENCODERTICKS_H
