// Generated by gencpp from file custom_msgs/WaypointRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_WAYPOINTREQUEST_H
#define CUSTOM_MSGS_MESSAGE_WAYPOINTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct WaypointRequest_
{
  typedef WaypointRequest_<ContainerAllocator> Type;

  WaypointRequest_()
    : index(0)  {
    }
  WaypointRequest_(const ContainerAllocator& _alloc)
    : index(0)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;





  typedef boost::shared_ptr< ::custom_msgs::WaypointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::WaypointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointRequest_

typedef ::custom_msgs::WaypointRequest_<std::allocator<void> > WaypointRequest;

typedef boost::shared_ptr< ::custom_msgs::WaypointRequest > WaypointRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::WaypointRequest const> WaypointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::WaypointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::WaypointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::WaypointRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::WaypointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::WaypointRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::WaypointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::WaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::WaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::WaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::WaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::WaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::WaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::WaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "483eea06cdc3e559421ee31116d0f3b9";
  }

  static const char* value(const ::custom_msgs::WaypointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x483eea06cdc3e559ULL;
  static const uint64_t static_value2 = 0x421ee31116d0f3b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::WaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/WaypointRequest";
  }

  static const char* value(const ::custom_msgs::WaypointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::WaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 index\n"
;
  }

  static const char* value(const ::custom_msgs::WaypointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::WaypointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::WaypointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::WaypointRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_WAYPOINTREQUEST_H
