// Generated by gencpp from file custom_msgs/Waypoint.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_WAYPOINT_H
#define CUSTOM_MSGS_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct Waypoint_
{
  typedef Waypoint_<ContainerAllocator> Type;

  Waypoint_()
    : lat(0.0)
    , lng(0.0)  {
    }
  Waypoint_(const ContainerAllocator& _alloc)
    : lat(0.0)
    , lng(0.0)  {
  (void)_alloc;
    }



   typedef float _lat_type;
  _lat_type lat;

   typedef float _lng_type;
  _lng_type lng;





  typedef boost::shared_ptr< ::custom_msgs::Waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::Waypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoint_

typedef ::custom_msgs::Waypoint_<std::allocator<void> > Waypoint;

typedef boost::shared_ptr< ::custom_msgs::Waypoint > WaypointPtr;
typedef boost::shared_ptr< ::custom_msgs::Waypoint const> WaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::Waypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::Waypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::custom_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return lhs.lat == rhs.lat &&
    lhs.lng == rhs.lng;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::custom_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "321bf96dbd44cdb44c4685a0ded4bea4";
  }

  static const char* value(const ::custom_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x321bf96dbd44cdb4ULL;
  static const uint64_t static_value2 = 0x4c4685a0ded4bea4ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/Waypoint";
  }

  static const char* value(const ::custom_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 lat\n"
"float32 lng\n"
;
  }

  static const char* value(const ::custom_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::Waypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lat);
      stream.next(m.lng);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::Waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::Waypoint_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "lat: ";
    Printer<float>::stream(s, indent + "  ", v.lat);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lng: ";
    Printer<float>::stream(s, indent + "  ", v.lng);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_WAYPOINT_H
